#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE app_owner LOGIN PASSWORD '$APP_OWNER_PASSWORD' NOSUPERUSER NOBYPASSRLS;
  CREATE ROLE app_runtime LOGIN PASSWORD '$APP_RUNTIME_PASSWORD' NOSUPERUSER NOBYPASSRLS;

  GRANT ALL ON SCHEMA public TO app_owner;
  GRANT USAGE ON SCHEMA public TO app_runtime;

  ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
  ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO app_runtime;
EOSQL
