export enum ErrorCode {
  // generic / fallback
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // auth-core (shared between customers/merchant-admins)
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_REFRESH_TOKEN = 'AUTH_MISSING_REFRESH_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_REFRESH_TOKEN_REUSE_DETECTED = 'AUTH_REFRESH_TOKEN_REUSE_DETECTED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_WRONG_TOKEN_AUDIENCE = 'AUTH_WRONG_TOKEN_AUDIENCE',
  AUTH_TOKEN_TENANT_MISMATCH = 'AUTH_TOKEN_TENANT_MISMATCH',
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
  AUTH_INVALID_ACCESS_TOKEN = 'AUTH_INVALID_ACCESS_TOKEN',

  // customers
  CUSTOMER_EMAIL_ALREADY_REGISTERED = 'CUSTOMER_EMAIL_ALREADY_REGISTERED',
  CUSTOMER_VERIFICATION_TOKEN_INVALID = 'CUSTOMER_VERIFICATION_TOKEN_INVALID',
  CUSTOMER_PASSWORD_RESET_TOKEN_INVALID = 'CUSTOMER_PASSWORD_RESET_TOKEN_INVALID',
  CUSTOMER_GOOGLE_ALREADY_LINKED = 'CUSTOMER_GOOGLE_ALREADY_LINKED',

  // merchant admins
  MERCHANT_ADMIN_EMAIL_ALREADY_REGISTERED = 'MERCHANT_ADMIN_EMAIL_ALREADY_REGISTERED',
  MERCHANT_ADMIN_INVITE_TOKEN_INVALID = 'MERCHANT_ADMIN_INVITE_TOKEN_INVALID',
  MERCHANT_ADMIN_VERIFICATION_TOKEN_INVALID = 'MERCHANT_ADMIN_VERIFICATION_TOKEN_INVALID',
  MERCHANT_ADMIN_PASSWORD_RESET_TOKEN_INVALID = 'MERCHANT_ADMIN_PASSWORD_RESET_TOKEN_INVALID',
  MERCHANT_ADMIN_NO_LONGER_EXISTS = 'MERCHANT_ADMIN_NO_LONGER_EXISTS',
  MERCHANT_ADMIN_NOT_FOUND = 'MERCHANT_ADMIN_NOT_FOUND',
  MERCHANT_ADMIN_ROLE_TOO_HIGH = 'MERCHANT_ADMIN_ROLE_TOO_HIGH',

  // oauth
  OAUTH_INVALID_STATE = 'OAUTH_INVALID_STATE',
  OAUTH_INVALID_OR_EXPIRED_CODE = 'OAUTH_INVALID_OR_EXPIRED_CODE',
  OAUTH_MISSING_ID_TOKEN = 'OAUTH_MISSING_ID_TOKEN',
  OAUTH_INVALID_ID_TOKEN_PAYLOAD = 'OAUTH_INVALID_ID_TOKEN_PAYLOAD',
  OAUTH_UNSUPPORTED_POPULATION = 'OAUTH_UNSUPPORTED_POPULATION',

  // carts & addresses
  CART_NOT_FOUND = 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  INVALID_CART_QUANTITY = 'INVALID_CART_QUANTITY',
  PRODUCT_VARIANT_NOT_FOUND = 'PRODUCT_VARIANT_NOT_FOUND',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE',

  // order & checkout
  GUEST_CHECKOUT_DISABLED = 'GUEST_CHECKOUT_DISABLED',
  CART_EMPTY = 'CART_EMPTY',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_EXPIRED = 'ORDER_EXPIRED',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  INVALID_ORDER_STATUS_TRANSITION = 'INVALID_ORDER_STATUS_TRANSITION',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUND_EXCEEDS_PAYMENT = 'REFUND_EXCEEDS_PAYMENT',

  // tenancy / common
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  INVALID_RETURN_URL = 'INVALID_RETURN_URL',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',

  // field-level validation — named after the class-validator constraint
  // they decode, uppercased/snake-cased (see fallbackCodeFor in
  // validation-field.ts, Task 3)
  IS_EMAIL = 'IS_EMAIL',
  IS_NOT_EMPTY = 'IS_NOT_EMPTY',
  IS_STRING = 'IS_STRING',
  IS_IN = 'IS_IN',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  IS_INT = 'IS_INT',
  MIN = 'MIN',
  MAX = 'MAX',
  IS_BOOLEAN = 'IS_BOOLEAN',
  IS_ARRAY = 'IS_ARRAY',
  IS_OBJECT = 'IS_OBJECT',
  IS_UUID = 'IS_UUID',
}
